- name: defragment windows disk asynchronously and launch AT API
  hosts: windows
  tasks:
    - name: Defragment all local volumes (in parallel)
      win_shell: C:\Users\claudio\Dropbox\Informatica\ansible-tower-4win\defrag.ps1
      async: 600
      poll: 0
      register: defrag_sleeper

    - name: check on async task
      async_status:
        jid: "{{ defrag_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
