- name: defragment windows disk asynchronously and launch AT API 
  hosts: windows
  tasks:
    - name: Defragment all local volumes (in parallel)
      win_shell: c:\Users\claudio\Desktop\defrag.ps1
      args:
        chdir: c:\Users\claudio\Desktop\
      async: 600
      poll: 0
      register: defrag_sleeper

    - name: check on async task
      async_status:
        jid: "{{ defrag_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
