- name: defragment windows disk asynchronously
  hosts: windows
  tasks:
    - name: Defragment all local volumes (in parallel)
      win_defrag:
        include_volumes: C
        priority: low
      async: 600
      poll: 0
      register: defrag_sleeper

    - name: check on async task
      async_status:
        jid: "{{ defrag_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
