- hosts: windows 
  handlers:
    - name: Defragment all local volumes (in parallel)
      win_defrag:
        include_volumes: C
        priority: low
      listen: "start tasks"
      async: 600
      poll: 30
    - name: check started services
      win_service:
        name: spooler
        state: started
      listen: "start tasks"

  tasks:
    - name: start tasks
      win_shell: explorer
      notify: "start tasks"
